### ISSUE TITLE
Unable to Load MLX Embedding Models from Hugging Face

### ISSUE THREAD

**Issue by keyboardstaff** [RamboRogers/mlx-gui#6]
I encountered issues while trying to load embedding models in MLX format. I attempted to use the following two models:
	1.	mlx-community/snowflake-arctic-embed-l-v2.0-bf16
	2.	mlx-community/multilingual-e5-large-mlx
However, both models failed to load. 

```
ERROR:mlx_gui.mlx_integration:Error loading model from /Users/xxx/.cache/mlx-gui/models--mlx-community--snowflake-arctic-embed-l-v2.0-bf16/snapshots/3da10e38e7875d6501adc14665c95b6708646121: Model type xlm-roberta not supported.
ERROR:mlx_gui.mlx_integration:Error loading model mlx-community/snowflake-arctic-embed-l-v2.0-bf16 from hub: Model type xlm-roberta not supported.
ERROR:mlx_gui.model_manager:❌ Non-memory error loading 'snowflake-arctic-embed-l-v2-0-bf16': Model type xlm-roberta not supported.
ERROR:mlx_gui.model_manager:Failed to load model snowflake-arctic-embed-l-v2-0-bf16: Model type xlm-roberta not supported.

```

```
ERROR:mlx_gui.mlx_integration:Error loading model from /Users/xxx/.cache/mlx-gui/models--mlx-community--multilingual-e5-large-mlx/snapshots/b4bd2129cc43ee99a7e91d3dc58374d33a3ce03b: Model type xlm-roberta not supported.
ERROR:mlx_gui.mlx_integration:Error loading model mlx-community/multilingual-e5-large-mlx from hub: Model type xlm-roberta not supported.
ERROR:mlx_gui.model_manager:❌ Non-memory error loading 'multilingual-e5-large-mlx': Model type xlm-roberta not supported.
ERROR:mlx_gui.model_manager:Failed to load model multilingual-e5-large-mlx: Model type xlm-roberta not supported.
```

**Comment by RamboRogers** [comment]
try Qwen3 models, I tested with those, I probably need to put an approved list -- I'm locked by mlx-lm and mlx-vlm as underpinning.  I'm debating on writing all new mlx bindings in rust, would need a project.

https://huggingface.co/mlx-community/Qwen3-Embedding-0.6B-4bit-DWQ

**Comment by keyboardstaff** [comment]
Haha, I'd be happy to help, but I don't know how to code yet!

**Comment by RamboRogers** [comment]
Fixed in 1.2.3

**Comment by keyboardstaff** [comment]
Despite various attempts, we are still encountering the same persistent errors when trying to use MLX community embedding models.

To address this ongoing compatibility challenge, we strongly recommend adopting the Blaizzy/mlx-embeddings GitHub project. This project has currently proven effective in resolving the runtime difficulties with MLX community embedding models, providing a reliable way to deploy and utilize them.
